apiVersion: v1
kind: ConfigMap
metadata:
  name: memory-box-config
data:
  DB_HOST: "memory-box-db"
  DEBUG: "false"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "http://localhost:30082,http://127.0.0.1:30082"
