apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - static-pvc.yaml
  - media-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - web-deployment.yaml
  - web-service.yaml
